apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: viewer
rules:
- apiGroups: ["*"]
  resources: ["secrets","configmaps","deployments","pods","services"]
  verbs: ["get", "watch", "list"]